blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/SoftDryzz/ProjectManager/blob/master/docs/USER_GUIDE.md
    about: Check the user guide for help and examples
  - name: ðŸ’¬ Discussions
    url: https://github.com/SoftDryzz/ProjectManager/discussions
    about: Ask questions and discuss ideas with the community